server.port=8083

reservations.service.url=http://reservations-demo:8080

spring.jackson.time-zone=America/Bogota
spring.jackson.serialization.write-dates-as-timestamps=false

vaadin.launch-browser=false
